Repository GoGo-tm/GoGo_Client, pull requests merged in 2022-10, with the labels that each got.

#97 refactor: next-auth
  pages/api/auth/[...nextauth].ts
  utils/token.ts
Labels: enhancement

#99 feat: add mylog wrap item
  components/mylogs/items.tsx
  types/mylogs.ts
Labels: enhancement

#102 feat: SWC 컴파일러로 마이그레이션
  .babelrc
  .gitignore
  components/banner.tsx
  components/button.tsx
  components/home/title.tsx
  components/mylogs/carousel.tsx
  components/mylogs/rate.tsx
  components/mylogs/tab.tsx
  components/navbar.tsx
  components/search.tsx
  next.config.js
  package.json
  pages/mylogs/create.tsx
  pages/profile/update.tsx
Labels: enhancement

#103 build: update next.config antd less
  next.config.js
  package.json
  pages/_app.tsx
  pages/auth/signUp.tsx
  types/next-auth.d.ts
Labels: enhancement

#104 feat: mypage 내 정보 수정 개선
  assets/svgs/pre.svg
  components/globalStyle.ts
  components/header.tsx
  components/layout.tsx
  pages/profile/update.tsx
Labels: enhancement

#105 feat: eslint 픽스
  .eslintrc.json
Labels: enhancement

#107 feat: 등산로 데이터 바인딩 및 경고 제거
  assets/svgs/heartSolid.svg
  components/boundaries/errorBoundary.tsx
  components/hikingMap.tsx
  components/home/guide.tsx
  components/listCard.tsx
  components/loading.tsx
  components/mylogs/items.tsx
  components/mylogs/searchDataList.tsx
  components/mylogs/tab.tsx
  components/navbar.tsx
  components/typography.tsx
  package-lock.json
  pages/auth/signUp.tsx
  pages/hiking/[id].tsx
  pages/mylogs/create.tsx
  pages/mylogs/index.tsx
  pages/profile/update.tsx
  types/mylogs.ts
  utils/misc.ts
Labels: enhancement

#111 fix: next.config console-error
  next.config.js
Labels: bug, enhancement

#114 feat: 등산로 페이지 및 린트 구체화
  .eslintrc.json
  assets/svgs/heartSolid.svg
  components/card.tsx
  package-lock.json
  package.json
  pages/hiking/index.tsx
  pages/index.tsx
Labels: 프론트엔드

#115 fix: button component forwardRef and add _document key attr
  components/button.tsx
  pages/_document.tsx
Labels: 버그, 프론트엔드
