Repository GoGo-tm/GoGo_Client, pull requests merged in 2022-08, with the labels that each got.

#6 feat: navbar 구현
  .babelrc
  components/layout.tsx
  components/navbar.tsx
  components/navlink.tsx
  constants/theme.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/hikings/index.tsx
  pages/index.tsx
  pages/mylogs/index.tsx
  pages/profile/index.tsx
  public/sw.js.map
  tsconfig.json
  types/assets.d.ts
  types/base.ts
  types/styled.d.ts
  yarn.lock
Labels: enhancement

#9 feat: header 추가
  components/header.tsx
  components/layout.tsx
  components/navbar.tsx
  mocks/handlers.ts
  pages/_app.tsx
  pages/hiking/index.tsx
  pages/hikings/index.tsx
  pages/index.tsx
  pages/mylogs/index.tsx
  pages/profile/index.tsx
  yarn.lock
Labels: enhancement

#12 chore: 네이버 맵 api로 데이터 패스 테스팅
  components/hikingMap.tsx
  package-lock.json
  package.json
  pages/_document.tsx
  pages/api/hello.ts
  pages/api/hiking.ts
  pages/hiking/[id].tsx
  utils/map.ts
  yarn.lock
Labels: enhancement

#13 feature: seo 컴포넌트 구현
  components/asyncBoundary.tsx
  components/errorBoundary.tsx
  components/navbar.tsx
  components/navlink.tsx
  components/seo.tsx
  pages/_app.tsx
  public/sw.js.map
Labels: enhancement

#14 chore: 초기 설정
  .babelrc
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  assets/antd.css
  components/asyncBoundary.tsx
  components/errorBoundary.tsx
  components/globalStyle.ts
  components/globalstyles.tsx
  components/header.tsx
  components/hikingMap.tsx
  components/layout.tsx
  components/navbar.tsx
  components/navlink.tsx
  components/onlyClient.tsx
  constants/theme.ts
  middleware.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hiking.ts
  pages/hiking/[id].tsx
  pages/hiking/index.tsx
  pages/index.tsx
  pages/mylogs/index.tsx
  pages/profile/index.tsx
  public/sw.js.map
  tsconfig.json
  yarn.lock
Labels: documentation

#15 style: font 추가
  components/globalStyle.ts
  components/navbar.tsx
  pages/_document.tsx
  pages/index.tsx
  public/fonts/Pretendard-Bold.otf
  public/fonts/Pretendard-ExtraBold.otf
  public/fonts/Pretendard-Medium.otf
  public/fonts/Pretendard-Regular.otf
  public/fonts/Pretendard-SemiBold.otf
  public/sw.js.map
Labels: enhancement

#17 feat: banner
  .babelrc
  components/banner.tsx
  components/navbar.tsx
  constants/queries.ts
  constants/weather.ts
  hooks/queries/useWeather.ts
  middleware.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/coords.ts
  pages/api/weather.ts
  pages/index.tsx
  public/sw.js.map
  svgs/hiking.svg
  svgs/home.svg
  svgs/location.svg
  svgs/mylog.svg
  svgs/profile.svg
  utils/map.ts
  utils/misc.ts
  utils/weather.ts
  yarn.lock
Labels: enhancement

#21 feat: home
  components/boundaries/asyncBoundary.tsx
  components/boundaries/errorBoundary.tsx
  components/boundaries/onlyClient.tsx
  components/divider.tsx
  components/home/section.tsx
  components/home/title.tsx
  components/search.tsx
  constants/weather.ts
  pages/_document.tsx
  pages/hiking/[id].tsx
  pages/index.tsx
  public/favicon.ico
  public/icons/android-icon-144x144.png
  public/icons/android-icon-192x192.png
  public/icons/android-icon-36x36.png
  public/icons/android-icon-48x48.png
  public/icons/android-icon-72x72.png
  public/icons/android-icon-96x96.png
  public/icons/apple-icon-114x114.png
  public/icons/apple-icon-120x120.png
  public/icons/apple-icon-144x144.png
  public/icons/apple-icon-152x152.png
  public/icons/apple-icon-180x180.png
  public/icons/apple-icon-57x57.png
  public/icons/apple-icon-60x60.png
  public/icons/apple-icon-72x72.png
  public/icons/apple-icon-76x76.png
  public/icons/apple-icon-precomposed.png
  public/icons/apple-icon.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
  public/icons/favicon.ico
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/icons/ms-icon-144x144.png
  public/icons/ms-icon-150x150.png
  public/icons/ms-icon-310x310.png
  public/icons/ms-icon-70x70.png
  public/images/thumbnail.png
  svgs/arrow.svg
  svgs/magnifier.svg
  utils/misc.ts
  utils/weather.ts
Labels: enhancement

#22 feat: Home 마크업 구현
  components/banner.tsx
  components/divider.tsx
  components/home/section.tsx
  components/home/title.tsx
  components/loading.tsx
  components/navbar.tsx
  components/search.tsx
  pages/index.tsx
  public/sw.js.map
  public/workbox-eac1af49.js.map
  svgs/right.svg
Labels: enhancement

#24 hotfix: 날씨 api 이슈
  .env.production
  components/banner.tsx
  hooks/queries/useWeather.ts
  middleware.ts
  pages/api/weather.ts
  pages/index.tsx
  utils/user.ts
  utils/weather.ts
Labels: bug

#26 feat: Card 컴포넌트 추가 및 등산로 구체화
  components/card.tsx
  pages/hiking/index.tsx
  public/images/Rectangle33.png
Labels: enhancement

#29 feat: cardList 컴포넌트 추가 및 hiking page 구체화
  components/card.tsx
  components/globalStyle.ts
  components/listCard.tsx
  pages/hiking/index.tsx
Labels: enhancement

#31 feat: 공통 컴포넌트 - Button/Protected
  components/button.tsx
  components/globalStyle.ts
  components/protected.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/profile/index.tsx
  yarn.lock
Labels: enhancement

#32 feat: auth 페이지 및 폴더 구조 변경
  assets/css/antd.css
  assets/svgs/apple.svg
  assets/svgs/arrow.svg
  assets/svgs/arrowSolid.svg
  assets/svgs/calendar.svg
  assets/svgs/circle.svg
  assets/svgs/circleX.svg
  assets/svgs/filter.svg
  assets/svgs/heartSolid.svg
  assets/svgs/hiking.svg
  assets/svgs/hikingList.svg
  assets/svgs/home.svg
  assets/svgs/inquiry.svg
  assets/svgs/kakao.svg
  assets/svgs/left.svg
  assets/svgs/likeOutline.svg
  assets/svgs/location.svg
  assets/svgs/magnifier.svg
  assets/svgs/mountain.svg
  assets/svgs/mylog.svg
  assets/svgs/mylogCamera.svg
  assets/svgs/naver.svg
  assets/svgs/notify.svg
  assets/svgs/profile.svg
  assets/svgs/profileModification.svg
  assets/svgs/right.svg
  assets/svgs/starLine.svg
  assets/svgs/starSolid.svg
  assets/svgs/x.svg
  components/auth/Input.tsx
  components/auth/Radio.tsx
  components/auth/styled.ts
  components/banner.tsx
  components/button.tsx
  components/divider.tsx
  components/globalStyle.ts
  components/home/title.tsx
  components/navbar.tsx
  components/protected.tsx
  components/search.tsx
  hooks/useForm.ts
  hooks/useInput.ts
  hooks/useUser.ts
  pages/_app.tsx
  pages/auth/signIn.tsx
  pages/auth/signUp.tsx
  utils/token.ts
  utils/user.ts
Labels: enhancement

#37 feat: 로그인/회원가입 폼 벨리데이터 추가
  components/auth/Input.tsx
  components/auth/authLabel.tsx
  components/auth/authRadio.tsx
  components/auth/styled.ts
  components/button.tsx
  hooks/useInput.ts
  pages/auth/signIn.tsx
  pages/auth/signUp.tsx
  utils/validator.ts
Labels: enhancement
