Repository GoGo-tm/GoGo_Client, pull requests merged in 2022-11, with the labels that each got.

#117 feat: add home searchbar api logic
  components/search.tsx
  pages/mylogs/index.tsx
Labels: 프론트엔드

#118 feat: hiking 데이터 연동 및 라우터 추가
  .pnp.cjs
  .yarn/cache/babel-plugin-import-npm-1.13.5-248523e80d-54d6a7e29c.zip
  .yarn/cache/babel-plugin-inline-react-svg-npm-2.0.1-829c5225c7-aa41d72283.zip
  .yarn/cache/lodash.isplainobject-npm-4.0.6-d73937742f-29c6351f28.zip
  components/card.tsx
  package.json
  pages/hiking/[id].tsx
  pages/hiking/index.tsx
  types/hikingTrails.ts
  yarn.lock
Labels: 프론트엔드

#120 feat: 내 정보 마무리
  components/header.tsx
  components/noticePost.tsx
  components/profile/myImage.tsx
  components/profile/profileNavlink.tsx
  pages/profile/contact.tsx
  pages/profile/index.tsx
  pages/profile/update.tsx
Labels: 프론트엔드, 유아이

#121 design: 레이아웃 망가짐 수정
  components/banner.tsx
  components/card.tsx
  components/mylogs/items.tsx
  pages/index.tsx
Labels: 유아이

#122 feat: 비밀번호 재설정 페이지 개발
  pages/auth/passwordReset.tsx
  pages/auth/signIn.tsx
  pages/hiking/index.tsx
  pages/index.tsx
  pages/profile/update.tsx
Labels: 프론트엔드

#123 feat: 내정보 API 추가
  components/banner.tsx
  constants/weather.ts
  pages/api/auth/[...nextauth].ts
  pages/profile/index.tsx
  types/user.ts
  utils/user.ts
Labels: 프론트엔드

#124 reafactor: api logic and error boundary
  components/navbar.tsx
  components/search.tsx
  pages/api/auth/[...nextauth].ts
  pages/auth/signIn.tsx
  pages/auth/signUp.tsx
  pages/mylogs/index.tsx
Labels: 프론트엔드

#127 feat: 404 page
  components/mylogs/tab.tsx
  pages/404.tsx
  pages/mylogs/index.tsx
  public/images/404.png
Labels: 프론트엔드

#130 hotfix: client error
  components/card.tsx
  pages/api/hikings.ts
  public/images/03_Splash.png
  public/images/08_Mountain1.png
  public/images/09_Mountain2.png
  public/images/11_Mountain4.png
  public/images/12_Mountain5.png
  public/images/Rectangle33.png
  types/hikingTrails.ts
Labels: 버그

#131 hotfix: client-error
  components/card.tsx
  pages/api/hikings.ts
  pages/hiking/index.tsx
  pages/index.tsx
Labels: 버그

#132 hotfix: client-error
  components/card.tsx
  pages/api/hikings.ts
Labels: 버그
